
# Kiro CLI pre block. Keep at the top of this file.
[[ -f "${HOME}/Library/Application Support/kiro-cli/shell/zshrc.pre.zsh" ]] && builtin source "${HOME}/Library/Application Support/kiro-cli/shell/zshrc.pre.zsh"

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="af-magic-zouchao"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# zstyle ':omz:plugins:nvm' autoload yes


# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.

plugins=(rails ruby autojump kubectl zsh-autosuggestions zsh-syntax-highlighting zsh-completions)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# brew
export PATH=/opt/homebrew/bin:$PATH

# rbenv
eval "$(rbenv init - zsh)"

# disable spring
export DISABLE_SPRING=true

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
# Load pyenv-virtualenv automatically by adding
eval "$(pyenv virtualenv-init -)"

# rsvm (rust)
[[ -s /Users/zzou/.rsvm/rsvm.sh ]] && . /Users/zzou/.rsvm/rsvm.sh # This loads RSVM

# autojump
[ -f /opt/homebrew/etc/profile.d/autojump.sh ] && . /opt/homebrew/etc/profile.d/autojump.sh

# lvim
export PATH=/Users/zzou/.local/bin:$PATH


# alias
alias vim=nvim
alias this_branch='git rev-parse --abbrev-ref HEAD'
alias gs='git status'
alias ga='git add'
alias grup='git remote update -p'
alias gd='git diff'
alias gc='git commit --verbose'
alias gl='git log'
alias gb='git branch'
alias glg='git log --graph'
alias gshow='git show'
alias gck='git checkout'
alias gpushthis='git push origin "$(this_branch)"'
alias gpullthis='git pull origin "$(this_branch)"'
alias gbm='git branch -m "$(this_branch)"'

# 敏感凭据（数据库密码 / token）在 ~/.config/zsh/secrets.zsh（git 忽略）
# 权威来源是 Bitwarden（Secure Note: zsh-secrets），换机/重装后用 `secrets-sync` 恢复
[ -f "$HOME/.config/zsh/secrets.zsh" ] && source "$HOME/.config/zsh/secrets.zsh"

# configuration zsh completion
fpath+=${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions/src

# sed 
export PATH="/opt/homebrew/opt/gnu-sed/libexec/gnubin:$PATH"

# mysql
export PATH="/opt/homebrew/opt/mysql-client/bin:$PATH"

export EDITOR="nvim"


# fnm
#FNM_PATH="/Users/zzou/Library/Application Support/fnm"
#if [ -d "$FNM_PATH" ]; then
#  export PATH="/Users/zzou/Library/Application Support/fnm:$PATH"
#  eval "`fnm env`"
#fi
# eval "$(fnm env --use-on-cd --shell zsh)"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
# export SDKMAN_DIR="$HOME/.sdkman"
# [[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# k8s
export KUBECTL_EXTERNAL_DIFF="colordiff -N -u"


# bun completions
[ -s "/Users/zzou/.bun/_bun" ] && source "/Users/zzou/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# asdf
. "$HOME/.asdf/asdf.sh"
. "$HOME/.asdf/plugins/java/set-java-home.zsh"
# export PATH="$HOME/.asdf/shims;$PATH"

# append completions to fpath
fpath=(${ASDF_DIR}/completions $fpath)
# initialise completions with ZSH's compinit
autoload -Uz compinit && compinit

# volta
#export VOLTA_HOME="$HOME/.volta"
#export PATH="$VOLTA_HOME/bin:$PATH"

# idea
# export PATH="/Applications/IntelliJ IDEA.app/Contents/MacOS:$PATH"



# set a function myip, canbe get ip address from any website
myip() {
    curl -s -4 cip.cc/$1
}

# set a function get_ip, canbe get ip address from any country


alias tailscale="/Applications/Tailscale.app/Contents/MacOS/Tailscale"



# raycast-proxy: 新终端自动继承代理开关状态（由 raycast-proxy 脚本维护）
[ -f "$HOME/.config/proxy-env.sh" ] && . "$HOME/.config/proxy-env.sh"
# raycast-proxy: VPN 抢占主服务时，先 ⌘Q 退出 Chrome 再执行 chromep
alias chromep='~/Code/Custom/raycast-proxy/chrome-proxy.sh'

# Kiro CLI post block. Keep at the bottom of this file.
[[ -f "${HOME}/Library/Application Support/kiro-cli/shell/zshrc.post.zsh" ]] && builtin source "${HOME}/Library/Application Support/kiro-cli/shell/zshrc.post.zsh"
alias ccd='claude --dangerously-skip-permissions'
alias tm='tmux'

# Added by codebase-memory-mcp install
export PATH="/Users/zzou/.local/bin:$PATH"

unproxy() {
	unset http_proxy
	unset HTTP_PROXY
	unset https_proxy
	unset HTTPS_PROXY
	unset ftp_proxy
	unset FTP_PROXY
	unset rsync_proxy
	unset RSYNC_PROXY
	unset ALL_PROXY
	unset all_proxy
	unset no_proxy
}


proxy(){
  export http_proxy="https://127.0.0.1:9870"
}
